[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "orthotune"
version = "0.1.0"
dependencies = [
    "openai==2.24.0",
    "python-dotenv==1.2.2",
    "pandas",
    "openpyxl",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
