LIMITATIONS_TEMPLATE = """You are an orthopedic researcher critically evaluating a study.

Given the title and introduction/background, methods, and results below, identify the limitations of this study.

Focus ONLY on limitations that affect the interpretation of the results (e.g. study design flaws, small sample size, selection bias, confounding variables, short follow-up, lack of control group, measurement issues).

Do NOT include:
- Suggestions for future work
- Strengths of the study
- General observations unrelated to result interpretation

Title: {title}

Full Text:
{full_text}

Provide a concise paragraph summarizing only the relevant limitations."""


def build_limitations_prompt(title: str, full_text: str) -> str:
    return LIMITATIONS_TEMPLATE.format(title=title, full_text=full_text)


EVAL_SYSTEM_PROMPT = """You are an expert researcher evaluating the quality of two limitations sections for a healthcare research study.

You will be given the introduction, methods, and results sections of a published journal article in the field of orthopedics, along with two anonymized limitations sections labeled A and B. One of these limitations sections was generated by AI, while the other was included in the published manuscript. You do not know which was written by an AI and which was published — evaluate them blindly and equally.

Your task:
1. For each section (A then B), identify every distinct sub-limitation mentioned.
2. For each sub-limitation, call insert_limitation_detail with your scores.
3. After scoring every sub-limitation across both sections, call insert_limitation_summary once with your verdict on each section.

Only consider limitations that affect the interpretation of the present study. Disregard any statements related to future work — these should not factor into your evaluation.

Scoring anchors — use these definitions to calibrate your scores:

Relevance (1–5):
  1 = Not relevant — addresses something not present in this study
  2 = Minimally relevant — tangentially related to the study design
  3 = Moderately relevant — addresses a real but minor design issue
  4 = Very relevant — addresses a significant design limitation
  5 = Extremely relevant — addresses a critical flaw that affects interpretation of the results

Critical Thinking (1–5):
  1 = Superficial — generic statement applicable to any study
  2 = Basic — identifies the issue but lacks depth or explanation
  3 = Adequate — explains why the limitation matters
  4 = Thoughtful — connects the limitation to specific results or conclusions
  5 = Sophisticated — discusses implications, alternative approaches, or mitigation strategies

Publishable (Y/N):
  Y = You would accept this limitation as written in a peer-reviewed orthopedic journal
  N = The limitation is too vague, incorrect, or adds no value to warrant publication

Hallucination (Y/N):
  Y = The limitation contains factually incorrect or fabricated claims that contradict the study text
  N = The limitation is factually consistent with the study text

Final summary — publishable_a and publishable_b:
  After scoring all sub-limitations, give an independent verdict for each section:
  publishable_a = Y if Limitation A as a whole is of sufficient quality to publish; N otherwise
  publishable_b = Y if Limitation B as a whole is of sufficient quality to publish; N otherwise"""

EVAL_USER_TEMPLATE = """Study Full Text:
{full_text}

---
Limitation A:
{lim_a}

---
Limitation B:
{lim_b}

---
PMID: {pmid}

Evaluate every sub-limitation in section A, then every sub-limitation in section B, calling insert_limitation_detail for each one. Then call insert_limitation_summary once with your final verdict."""


def build_eval_prompt(full_text: str, lim_a: str, lim_b: str, pmid: int) -> str:
    return EVAL_USER_TEMPLATE.format(full_text=full_text, lim_a=lim_a, lim_b=lim_b, pmid=pmid)
